Environent variable inaccessible in SSH fix

diff --git a/files/usr/bin/grc b/files/usr/bin/grc
--- a/files/usr/bin/grc
+++ b/files/usr/bin/grc
@@ -1,6 +1,13 @@
 #!/bin/bash
 
-GRC_CMD="/usr/bin/gridcoinresearchd -rpcuser=$GRC_USERNAME -rpcpassword=$GRC_PASSWD"
+if [ ! -z GRC_USERNAME ]; then
+	USERNAME="-rpcuser=$GRC_USERNAME"
+fi
+if [ ! -z GRC_PASSWD ]; then
+	PASSWORD="-rpcpassword=$GRC_PASSWD"
+fi
+GRC_CMD="/usr/bin/gridcoinresearchd $USERNAME $PASSWD"
+
 LOGFILE="$GRC_DATADIR/debug.log"
 
 case $1 in
@@ -18,9 +25,8 @@ c|cmd)
 	;;
 
 d|clear|delete)
-	clear
 	echo "" > $LOGFILE
-	clear
+	echo '[GRC]d gridcoinresearchd debug log cleared'
 	;;
 
 h|height)
@@ -31,56 +37,77 @@ h|height)
 	;;
 
 i|init|start)
+	# Abort when GRC client currently running
+	if pgrep gridcoinres ; then
+		echo -e '[GRC]i [ABORT: 1] gridcoinresearchd already running'
+		exit 1
+	fi
+
+	# Abort when .GridcoinResearch folder is not correctly mounted
+	if [ ! -f $GRC_DATADIR/gridcoinresearch.conf ] ; then
+		echo -e '[GRC]i [ABORT: 2] gridcoinresearch.conf NOT FOUND'
+		exit 2
+	fi
+
 	# Wipe $GRC_DATADIR/debug.log
+	echo "[GRC]i Wiping gridcoinresearchd log"
 	if [ -f $GRC_DATADIR/debug.log ] ; then
 		rm -r $GRC_DATADIR/debug.log
 	fi
 	touch $GRC_DATADIR/debug.log
 
-	# Launch process
-	if ! pgrep "gridcoinresearchd" ; then
-		# Start Gridcoin client
-		if [ -f $GRC_DATADIR/gridcoinresearch.conf ] ; then
-			# .GridcoinResearch folder is correctly mounted
-			#/usr/bin/gridcoinresearchd -daemon -server -shrinkdebugfile -upnp -blocknotify='exec /grcupdate.sh' \
-			echo "[GRC] executing gridcoinresearchd"
-			/usr/bin/gridcoinresearchd -server -shrinkdebugfile -upnp -blocknotify="exec /grcupdate.sh $GRC_USERNAME $GRC_PASSWD"
+	# .GridcoinResearch folder is correctly mounted
+	#/usr/bin/gridcoinresearchd -daemon -server -shrinkdebugfile -upnp -blocknotify='exec /grcupdate.sh' \
+
+	# Check credential validity and start process
+	echo "[GRC]i checking credentials"
+	GRC_RUNOPT="-server -upnp"
+	if [ -z $2 ] || [ -z $3 ] ; then
+		if [ -z $GRC_USERNAME ] || [ -z $GRC_PASSWD ] ; then
+			echo "[GRC]i Credential not set ENV"
+			echo "[GRC]i [ABORT: 3] Credential not given"
+			exit 3
 		else
-			echo -e '[GRC] gridcoinresearch.conf NOT FOUND, aborting'
+			echo "[GRC]i Credential not explicitly given; using ENV; USERNAME=$GRC_USERNAME PASSWD=$GRC_PASSWD"
+			GRC_RUNOPT=$GRC_RUNOPT -blocknotify=\"/grcupdate.sh $GRC_USERNAME $GRC_PASSWD\"
 		fi
 	else
-		# Gridcoin client already running; "do nothing".
-		# Uncomment below to specify what to do
-		#/usr/bin/gridcoinresearchd $@
-		echo -e '[GRC] gridcoinresearchd already running!'
+		echo "[GRC]i Credential given; USERNAME=$2 PASSWD=$3"
+		GRC_RUNOPT=$GRC_RUNOPT -blocknotify=\"/grcupdate.sh $2 $3\"
 	fi
+	echo "[GRC]i executing gridcoinresearchd with OPT: $GRC_RUNOPT"
+	/usr/bin/gridcoinresearchd $GRC_RUNOPT
+	exit 0
 	;;
 
 k|kill)
-	killall gridcoinresearchd
-	echo Forcing gridcoinresearchd stop
+	echo "[GRC]k Force stop gridcoinresearchd"
+	pkill gridcoinresearchd
 	ps -e | grep gridcoin
 	;;
 
 l|log)
 	clear
+	echo "[GRC]l gridcoinresearchd debug log"
 	tail -f -n 80 $LOGFILE
 	clear
 	;;
 
 s|stop|exit)
 	$GRC_CMD stop
-	echo Stopping gridcoinresearchd
+	echo "[GRC]s Stopping gridcoinresearchd"
 	ps -e | grep gridcoin
 	;;
 
 v|check|status)
+	echo "[GRC]v Running gridcoinresearchd process:"
 	ps -e | grep gridcoin
+	echo ''
 	;;
 
 
 *)
-	echo "gridcoinresearchd command wrapper"
+	echo "[GRC] gridcoinresearchd command wrapper"
 	echo "Usage: grc [options]"
 	echo ""
 	echo "options:"
